name: true
#markdown: GFM
#kramdown:
#  parse_block_html: true


# Social Media
social_links:
  github: niko-la
  linkedin: kava
  twitter: diynikola


  # Timezone
timezone: America/New_York

# Additional SEO Settings
lang: en
locale: en_US

#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one